//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaXML
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public string uuid { get; set; }
        public string rfc { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> isr { get; set; }
        public Nullable<System.DateTime> fechainicialpago { get; set; }
        public Nullable<System.DateTime> fechafinalpago { get; set; }
        public Nullable<System.DateTime> fecha_timbrado { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public Nullable<bool> esCancelado { get; set; }
        public string path { get; set; }
        public Nullable<decimal> reintegroISR { get; set; }
    }
}
