//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2.OrdenChangeStatus {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://goepower.com/", ConfigurationName="OrdenChangeStatus.productioncallsSoap")]
    public interface productioncallsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://goepower.com/StatusToProduction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int StatusToProduction();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://goepower.com/StatusToProduction", ReplyAction="*")]
        System.Threading.Tasks.Task<int> StatusToProductionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://goepower.com/StatusToShipping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int StatusToShipping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://goepower.com/StatusToShipping", ReplyAction="*")]
        System.Threading.Tasks.Task<int> StatusToShippingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://goepower.com/StatusToBilling", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int StatusToBilling();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://goepower.com/StatusToBilling", ReplyAction="*")]
        System.Threading.Tasks.Task<int> StatusToBillingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://goepower.com/StatusToCompleted", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int StatusToCompleted();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://goepower.com/StatusToCompleted", ReplyAction="*")]
        System.Threading.Tasks.Task<int> StatusToCompletedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://goepower.com/StatusRelease", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int StatusRelease();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://goepower.com/StatusRelease", ReplyAction="*")]
        System.Threading.Tasks.Task<int> StatusReleaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://goepower.com/StatusCancel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int StatusCancel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://goepower.com/StatusCancel", ReplyAction="*")]
        System.Threading.Tasks.Task<int> StatusCancelAsync();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje ChangeStatusRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://goepower.com/ChangeStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApplication2.OrdenChangeStatus.ChangeStatusResponse ChangeStatus(ConsoleApplication2.OrdenChangeStatus.ChangeStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://goepower.com/ChangeStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication2.OrdenChangeStatus.ChangeStatusResponse> ChangeStatusAsync(ConsoleApplication2.OrdenChangeStatus.ChangeStatusRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://goepower.com/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string masterKeyField;
        
        private int producerIDField;
        
        private int companyIDField;
        
        private string orderIDsField;
        
        private ePowerOrderStatus statusField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MasterKey {
            get {
                return this.masterKeyField;
            }
            set {
                this.masterKeyField = value;
                this.RaisePropertyChanged("MasterKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ProducerID {
            get {
                return this.producerIDField;
            }
            set {
                this.producerIDField = value;
                this.RaisePropertyChanged("ProducerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
                this.RaisePropertyChanged("CompanyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OrderIDs {
            get {
                return this.orderIDsField;
            }
            set {
                this.orderIDsField = value;
                this.RaisePropertyChanged("OrderIDs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ePowerOrderStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://goepower.com/")]
    public enum ePowerOrderStatus {
        
        /// <remarks/>
        Release,
        
        /// <remarks/>
        ToProduction,
        
        /// <remarks/>
        ToShipping,
        
        /// <remarks/>
        ToBilling,
        
        /// <remarks/>
        ToCompleted,
        
        /// <remarks/>
        Cancel,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://goepower.com/")]
    public partial class AuthReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int producerIDField;
        
        private int companyIDField;
        
        private bool isSuccessfulField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ProducerID {
            get {
                return this.producerIDField;
            }
            set {
                this.producerIDField = value;
                this.RaisePropertyChanged("ProducerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
                this.RaisePropertyChanged("CompanyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsSuccessful {
            get {
                return this.isSuccessfulField;
            }
            set {
                this.isSuccessfulField = value;
                this.RaisePropertyChanged("IsSuccessful");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeStatus", WrapperNamespace="http://goepower.com/", IsWrapped=true)]
    public partial class ChangeStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://goepower.com/")]
        public ConsoleApplication2.OrdenChangeStatus.AuthHeader AuthHeader;
        
        public ChangeStatusRequest() {
        }
        
        public ChangeStatusRequest(ConsoleApplication2.OrdenChangeStatus.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeStatusResponse", WrapperNamespace="http://goepower.com/", IsWrapped=true)]
    public partial class ChangeStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://goepower.com/", Order=0)]
        public ConsoleApplication2.OrdenChangeStatus.AuthReturn ChangeStatusResult;
        
        public ChangeStatusResponse() {
        }
        
        public ChangeStatusResponse(ConsoleApplication2.OrdenChangeStatus.AuthReturn ChangeStatusResult) {
            this.ChangeStatusResult = ChangeStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface productioncallsSoapChannel : ConsoleApplication2.OrdenChangeStatus.productioncallsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class productioncallsSoapClient : System.ServiceModel.ClientBase<ConsoleApplication2.OrdenChangeStatus.productioncallsSoap>, ConsoleApplication2.OrdenChangeStatus.productioncallsSoap {
        
        public productioncallsSoapClient() {
        }
        
        public productioncallsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public productioncallsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public productioncallsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public productioncallsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int StatusToProduction() {
            return base.Channel.StatusToProduction();
        }
        
        public System.Threading.Tasks.Task<int> StatusToProductionAsync() {
            return base.Channel.StatusToProductionAsync();
        }
        
        public int StatusToShipping() {
            return base.Channel.StatusToShipping();
        }
        
        public System.Threading.Tasks.Task<int> StatusToShippingAsync() {
            return base.Channel.StatusToShippingAsync();
        }
        
        public int StatusToBilling() {
            return base.Channel.StatusToBilling();
        }
        
        public System.Threading.Tasks.Task<int> StatusToBillingAsync() {
            return base.Channel.StatusToBillingAsync();
        }
        
        public int StatusToCompleted() {
            return base.Channel.StatusToCompleted();
        }
        
        public System.Threading.Tasks.Task<int> StatusToCompletedAsync() {
            return base.Channel.StatusToCompletedAsync();
        }
        
        public int StatusRelease() {
            return base.Channel.StatusRelease();
        }
        
        public System.Threading.Tasks.Task<int> StatusReleaseAsync() {
            return base.Channel.StatusReleaseAsync();
        }
        
        public int StatusCancel() {
            return base.Channel.StatusCancel();
        }
        
        public System.Threading.Tasks.Task<int> StatusCancelAsync() {
            return base.Channel.StatusCancelAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication2.OrdenChangeStatus.ChangeStatusResponse ConsoleApplication2.OrdenChangeStatus.productioncallsSoap.ChangeStatus(ConsoleApplication2.OrdenChangeStatus.ChangeStatusRequest request) {
            return base.Channel.ChangeStatus(request);
        }
        
        public ConsoleApplication2.OrdenChangeStatus.AuthReturn ChangeStatus(ConsoleApplication2.OrdenChangeStatus.AuthHeader AuthHeader) {
            ConsoleApplication2.OrdenChangeStatus.ChangeStatusRequest inValue = new ConsoleApplication2.OrdenChangeStatus.ChangeStatusRequest();
            inValue.AuthHeader = AuthHeader;
            ConsoleApplication2.OrdenChangeStatus.ChangeStatusResponse retVal = ((ConsoleApplication2.OrdenChangeStatus.productioncallsSoap)(this)).ChangeStatus(inValue);
            return retVal.ChangeStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication2.OrdenChangeStatus.ChangeStatusResponse> ConsoleApplication2.OrdenChangeStatus.productioncallsSoap.ChangeStatusAsync(ConsoleApplication2.OrdenChangeStatus.ChangeStatusRequest request) {
            return base.Channel.ChangeStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication2.OrdenChangeStatus.ChangeStatusResponse> ChangeStatusAsync(ConsoleApplication2.OrdenChangeStatus.AuthHeader AuthHeader) {
            ConsoleApplication2.OrdenChangeStatus.ChangeStatusRequest inValue = new ConsoleApplication2.OrdenChangeStatus.ChangeStatusRequest();
            inValue.AuthHeader = AuthHeader;
            return ((ConsoleApplication2.OrdenChangeStatus.productioncallsSoap)(this)).ChangeStatusAsync(inValue);
        }
    }
}
