//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraIntelisis
    {
        public int id_bitacora { get; set; }
        public Nullable<int> numero_orden { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    }
}
