//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteEstadoCuenta
    {
        public int numero_dealer { get; set; }
        public string concesionaria { get; set; }
        public string fullname { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<decimal> ajuste { get; set; }
        public Nullable<int> webUserID { get; set; }
        public string email { get; set; }
    }
}
