//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstadoCuentaSAAMEntities : DbContext
    {
        public EstadoCuentaSAAMEntities()
            : base("name=EstadoCuentaSAAMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClienteEstadoCuenta> Cliente { get; set; }
        public virtual DbSet<OrdenEstadoCuenta> Orden { get; set; }
        public virtual DbSet<TiendaEstadoCuenta> Tienda { get; set; }
        public virtual DbSet<ClienteExcluyente> ClienteExcluyente { get; set; }
        public virtual DbSet<BitacoraIntelisis> BitacoraIntelisis { get; set; }
        public virtual DbSet<Ejecucion> Ejecucion { get; set; }
    }
}
