#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Goepower")]
	public partial class GoepowerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertItem(Item instance);
    partial void UpdateItem(Item instance);
    partial void DeleteItem(Item instance);
    partial void InsertOrden(Orden instance);
    partial void UpdateOrden(Orden instance);
    partial void DeleteOrden(Orden instance);
    partial void InsertOrdenArchivos(OrdenArchivos instance);
    partial void UpdateOrdenArchivos(OrdenArchivos instance);
    partial void DeleteOrdenArchivos(OrdenArchivos instance);
    partial void InsertOrdenFacturacion(OrdenFacturacion instance);
    partial void UpdateOrdenFacturacion(OrdenFacturacion instance);
    partial void DeleteOrdenFacturacion(OrdenFacturacion instance);
    #endregion
		
		public GoepowerDataContext() : 
				base(global::ConsoleApplication2.Properties.Settings.Default.GoepowerConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public GoepowerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GoepowerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GoepowerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GoepowerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Item> Item
		{
			get
			{
				return this.GetTable<Item>();
			}
		}
		
		public System.Data.Linq.Table<Orden> Orden
		{
			get
			{
				return this.GetTable<Orden>();
			}
		}
		
		public System.Data.Linq.Table<OrdenArchivos> OrdenArchivos
		{
			get
			{
				return this.GetTable<OrdenArchivos>();
			}
		}
		
		public System.Data.Linq.Table<OrdenFacturacion> OrdenFacturacion
		{
			get
			{
				return this.GetTable<OrdenFacturacion>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Item")]
	public partial class Item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ordenID;
		
		private string _sku;
		
		private System.Nullable<double> _precio;
		
		private string _descripcion;
		
		private System.Nullable<int> _cantidad;
		
		private int _itemID;
		
		private System.Nullable<int> _records;
		
		private System.Nullable<int> _setSize;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnordenIDChanging(string value);
    partial void OnordenIDChanged();
    partial void OnskuChanging(string value);
    partial void OnskuChanged();
    partial void OnprecioChanging(System.Nullable<double> value);
    partial void OnprecioChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OncantidadChanging(System.Nullable<int> value);
    partial void OncantidadChanged();
    partial void OnitemIDChanging(int value);
    partial void OnitemIDChanged();
    partial void OnrecordsChanging(System.Nullable<int> value);
    partial void OnrecordsChanged();
    partial void OnsetSizeChanging(System.Nullable<int> value);
    partial void OnsetSizeChanged();
    #endregion
		
		public Item()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ordenID", DbType="VarChar(20)")]
		public string ordenID
		{
			get
			{
				return this._ordenID;
			}
			set
			{
				if ((this._ordenID != value))
				{
					this.OnordenIDChanging(value);
					this.SendPropertyChanging();
					this._ordenID = value;
					this.SendPropertyChanged("ordenID");
					this.OnordenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sku", DbType="VarChar(50)")]
		public string sku
		{
			get
			{
				return this._sku;
			}
			set
			{
				if ((this._sku != value))
				{
					this.OnskuChanging(value);
					this.SendPropertyChanging();
					this._sku = value;
					this.SendPropertyChanged("sku");
					this.OnskuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Float")]
		public System.Nullable<double> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(100)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int")]
		public System.Nullable<int> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int itemID
		{
			get
			{
				return this._itemID;
			}
			set
			{
				if ((this._itemID != value))
				{
					this.OnitemIDChanging(value);
					this.SendPropertyChanging();
					this._itemID = value;
					this.SendPropertyChanged("itemID");
					this.OnitemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_records", DbType="Int")]
		public System.Nullable<int> records
		{
			get
			{
				return this._records;
			}
			set
			{
				if ((this._records != value))
				{
					this.OnrecordsChanging(value);
					this.SendPropertyChanging();
					this._records = value;
					this.SendPropertyChanged("records");
					this.OnrecordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_setSize", DbType="Int")]
		public System.Nullable<int> setSize
		{
			get
			{
				return this._setSize;
			}
			set
			{
				if ((this._setSize != value))
				{
					this.OnsetSizeChanging(value);
					this.SendPropertyChanging();
					this._setSize = value;
					this.SendPropertyChanged("setSize");
					this.OnsetSizeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Orden")]
	public partial class Orden : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ordenID;
		
		private System.Nullable<int> _webUserID;
		
		private string _tienda;
		
		private System.Nullable<System.DateTime> _orderDate;
		
		private string _status;
		
		private System.Nullable<System.DateTime> _releaseDate;
		
		private System.Nullable<System.DateTime> _shippingDate;
		
		private System.Nullable<System.DateTime> _completeDate;
		
		private System.Nullable<bool> _pagado;
		
		private System.Nullable<double> _Total;
		
		private string _clienteIntelisis;
		
		private System.Xml.Linq.XElement _detalle;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnordenIDChanging(string value);
    partial void OnordenIDChanged();
    partial void OnwebUserIDChanging(System.Nullable<int> value);
    partial void OnwebUserIDChanged();
    partial void OntiendaChanging(string value);
    partial void OntiendaChanged();
    partial void OnorderDateChanging(System.Nullable<System.DateTime> value);
    partial void OnorderDateChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnreleaseDateChanging(System.Nullable<System.DateTime> value);
    partial void OnreleaseDateChanged();
    partial void OnshippingDateChanging(System.Nullable<System.DateTime> value);
    partial void OnshippingDateChanged();
    partial void OncompleteDateChanging(System.Nullable<System.DateTime> value);
    partial void OncompleteDateChanged();
    partial void OnpagadoChanging(System.Nullable<bool> value);
    partial void OnpagadoChanged();
    partial void OnTotalChanging(System.Nullable<double> value);
    partial void OnTotalChanged();
    partial void OnclienteIntelisisChanging(string value);
    partial void OnclienteIntelisisChanged();
    partial void OndetalleChanging(System.Xml.Linq.XElement value);
    partial void OndetalleChanged();
    #endregion
		
		public Orden()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ordenID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ordenID
		{
			get
			{
				return this._ordenID;
			}
			set
			{
				if ((this._ordenID != value))
				{
					this.OnordenIDChanging(value);
					this.SendPropertyChanging();
					this._ordenID = value;
					this.SendPropertyChanged("ordenID");
					this.OnordenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_webUserID", DbType="Int")]
		public System.Nullable<int> webUserID
		{
			get
			{
				return this._webUserID;
			}
			set
			{
				if ((this._webUserID != value))
				{
					this.OnwebUserIDChanging(value);
					this.SendPropertyChanging();
					this._webUserID = value;
					this.SendPropertyChanged("webUserID");
					this.OnwebUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tienda", DbType="VarChar(50)")]
		public string tienda
		{
			get
			{
				return this._tienda;
			}
			set
			{
				if ((this._tienda != value))
				{
					this.OntiendaChanging(value);
					this.SendPropertyChanging();
					this._tienda = value;
					this.SendPropertyChanged("tienda");
					this.OntiendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> orderDate
		{
			get
			{
				return this._orderDate;
			}
			set
			{
				if ((this._orderDate != value))
				{
					this.OnorderDateChanging(value);
					this.SendPropertyChanging();
					this._orderDate = value;
					this.SendPropertyChanged("orderDate");
					this.OnorderDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(20)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_releaseDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> releaseDate
		{
			get
			{
				return this._releaseDate;
			}
			set
			{
				if ((this._releaseDate != value))
				{
					this.OnreleaseDateChanging(value);
					this.SendPropertyChanging();
					this._releaseDate = value;
					this.SendPropertyChanged("releaseDate");
					this.OnreleaseDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shippingDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> shippingDate
		{
			get
			{
				return this._shippingDate;
			}
			set
			{
				if ((this._shippingDate != value))
				{
					this.OnshippingDateChanging(value);
					this.SendPropertyChanging();
					this._shippingDate = value;
					this.SendPropertyChanged("shippingDate");
					this.OnshippingDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_completeDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> completeDate
		{
			get
			{
				return this._completeDate;
			}
			set
			{
				if ((this._completeDate != value))
				{
					this.OncompleteDateChanging(value);
					this.SendPropertyChanging();
					this._completeDate = value;
					this.SendPropertyChanged("completeDate");
					this.OncompleteDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pagado", DbType="Bit")]
		public System.Nullable<bool> pagado
		{
			get
			{
				return this._pagado;
			}
			set
			{
				if ((this._pagado != value))
				{
					this.OnpagadoChanging(value);
					this.SendPropertyChanging();
					this._pagado = value;
					this.SendPropertyChanged("pagado");
					this.OnpagadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Float")]
		public System.Nullable<double> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clienteIntelisis", DbType="VarChar(50)")]
		public string clienteIntelisis
		{
			get
			{
				return this._clienteIntelisis;
			}
			set
			{
				if ((this._clienteIntelisis != value))
				{
					this.OnclienteIntelisisChanging(value);
					this.SendPropertyChanging();
					this._clienteIntelisis = value;
					this.SendPropertyChanged("clienteIntelisis");
					this.OnclienteIntelisisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detalle", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement detalle
		{
			get
			{
				return this._detalle;
			}
			set
			{
				if ((this._detalle != value))
				{
					this.OndetalleChanging(value);
					this.SendPropertyChanging();
					this._detalle = value;
					this.SendPropertyChanged("detalle");
					this.OndetalleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrdenArchivos")]
	public partial class OrdenArchivos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_ordenArchivos;
		
		private string _ordenID;
		
		private System.Nullable<byte> _plantillasDescargadas;
		
		private string _tienda;
		
		private System.Xml.Linq.XElement _detalle;
		
		private System.Nullable<System.DateTime> _fecha_descarga;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ordenArchivosChanging(int value);
    partial void Onid_ordenArchivosChanged();
    partial void OnordenIDChanging(string value);
    partial void OnordenIDChanged();
    partial void OnplantillasDescargadasChanging(System.Nullable<byte> value);
    partial void OnplantillasDescargadasChanged();
    partial void OntiendaChanging(string value);
    partial void OntiendaChanged();
    partial void OndetalleChanging(System.Xml.Linq.XElement value);
    partial void OndetalleChanged();
    partial void Onfecha_descargaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_descargaChanged();
    #endregion
		
		public OrdenArchivos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ordenArchivos", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_ordenArchivos
		{
			get
			{
				return this._id_ordenArchivos;
			}
			set
			{
				if ((this._id_ordenArchivos != value))
				{
					this.Onid_ordenArchivosChanging(value);
					this.SendPropertyChanging();
					this._id_ordenArchivos = value;
					this.SendPropertyChanged("id_ordenArchivos");
					this.Onid_ordenArchivosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ordenID", DbType="VarChar(50)")]
		public string ordenID
		{
			get
			{
				return this._ordenID;
			}
			set
			{
				if ((this._ordenID != value))
				{
					this.OnordenIDChanging(value);
					this.SendPropertyChanging();
					this._ordenID = value;
					this.SendPropertyChanged("ordenID");
					this.OnordenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plantillasDescargadas", DbType="TinyInt")]
		public System.Nullable<byte> plantillasDescargadas
		{
			get
			{
				return this._plantillasDescargadas;
			}
			set
			{
				if ((this._plantillasDescargadas != value))
				{
					this.OnplantillasDescargadasChanging(value);
					this.SendPropertyChanging();
					this._plantillasDescargadas = value;
					this.SendPropertyChanged("plantillasDescargadas");
					this.OnplantillasDescargadasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tienda", DbType="VarChar(50)")]
		public string tienda
		{
			get
			{
				return this._tienda;
			}
			set
			{
				if ((this._tienda != value))
				{
					this.OntiendaChanging(value);
					this.SendPropertyChanging();
					this._tienda = value;
					this.SendPropertyChanged("tienda");
					this.OntiendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detalle", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement detalle
		{
			get
			{
				return this._detalle;
			}
			set
			{
				if ((this._detalle != value))
				{
					this.OndetalleChanging(value);
					this.SendPropertyChanging();
					this._detalle = value;
					this.SendPropertyChanged("detalle");
					this.OndetalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_descarga", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_descarga
		{
			get
			{
				return this._fecha_descarga;
			}
			set
			{
				if ((this._fecha_descarga != value))
				{
					this.Onfecha_descargaChanging(value);
					this.SendPropertyChanging();
					this._fecha_descarga = value;
					this.SendPropertyChanged("fecha_descarga");
					this.Onfecha_descargaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrdenFacturacion")]
	public partial class OrdenFacturacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _numero_orden;
		
		private System.Nullable<System.DateTime> _fecha_registro;
		
		private System.Xml.Linq.XElement _detalle;
		
		private string _tienda;
		
		private System.Nullable<decimal> _Importe;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnumero_ordenChanging(int value);
    partial void Onnumero_ordenChanged();
    partial void Onfecha_registroChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_registroChanged();
    partial void OndetalleChanging(System.Xml.Linq.XElement value);
    partial void OndetalleChanged();
    partial void OntiendaChanging(string value);
    partial void OntiendaChanged();
    partial void OnImporteChanging(System.Nullable<decimal> value);
    partial void OnImporteChanged();
    #endregion
		
		public OrdenFacturacion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_orden", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int numero_orden
		{
			get
			{
				return this._numero_orden;
			}
			set
			{
				if ((this._numero_orden != value))
				{
					this.Onnumero_ordenChanging(value);
					this.SendPropertyChanging();
					this._numero_orden = value;
					this.SendPropertyChanged("numero_orden");
					this.Onnumero_ordenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this.Onfecha_registroChanging(value);
					this.SendPropertyChanging();
					this._fecha_registro = value;
					this.SendPropertyChanged("fecha_registro");
					this.Onfecha_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detalle", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement detalle
		{
			get
			{
				return this._detalle;
			}
			set
			{
				if ((this._detalle != value))
				{
					this.OndetalleChanging(value);
					this.SendPropertyChanging();
					this._detalle = value;
					this.SendPropertyChanged("detalle");
					this.OndetalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tienda", DbType="VarChar(100)")]
		public string tienda
		{
			get
			{
				return this._tienda;
			}
			set
			{
				if ((this._tienda != value))
				{
					this.OntiendaChanging(value);
					this.SendPropertyChanging();
					this._tienda = value;
					this.SendPropertyChanged("tienda");
					this.OntiendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Importe", DbType="Money")]
		public System.Nullable<decimal> Importe
		{
			get
			{
				return this._Importe;
			}
			set
			{
				if ((this._Importe != value))
				{
					this.OnImporteChanging(value);
					this.SendPropertyChanging();
					this._Importe = value;
					this.SendPropertyChanged("Importe");
					this.OnImporteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
