//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenEstadoCuenta
    {
        public int numero_orden { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<bool> esCampana { get; set; }
        public string BillingMethod { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string estatus { get; set; }
        public Nullable<int> webUserID { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> BillingDate { get; set; }
        public Nullable<int> id_tienda { get; set; }
    
        public virtual TiendaEstadoCuenta Tienda { get; set; }
    }
}
