//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoSAAM
    {
        public string sku { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> inventario { get; set; }
        public string proyeccion { get; set; }
        public Nullable<int> piezas_paquete { get; set; }
        public string img_miniatura { get; set; }
        public Nullable<int> id_tienda { get; set; }
        public int id_producto { get; set; }
    
        public virtual TiendaSAAM Tienda { get; set; }
    }
}
