//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReporteSAAMEntities : DbContext
    {
        public ReporteSAAMEntities()
            : base("name=ReporteSAAMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClienteSAAM> Cliente { get; set; }
        public virtual DbSet<ItemSAAM> Item { get; set; }
        public virtual DbSet<OrdenSAAM> Orden { get; set; }
        public virtual DbSet<ProductoSAAM> Producto { get; set; }
        public virtual DbSet<TiendaSAAM> Tienda { get; set; }
    }
}
